linter:
  rules:
    # Make constructors the first thing in every class
    - sort_constructors_first

    # The new tabs vs. spaces. Choose wisely
    - prefer_single_quotes

    # Back to the 80s
    - lines_longer_than_80_chars

    - avoid_annotating_with_dynamic
